# Generated by Django 4.2.7 on 2026-05-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_and_patient_fields'),
        ('core', '0005_patient_booking_locks_and_meeting'),
    ]

    operations = [
    ]
