# Generated by Django 4.2.7 on 2026-05-03 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_doctor_facility_specialties(apps, schema_editor):
    FacilitySpecialty = apps.get_model("core", "FacilitySpecialty")
    ProviderProfile = apps.get_model("core", "ProviderProfile")
    ProviderMembership = apps.get_model("core", "ProviderMembership")

    doctor_role = "doctor"
    for m in (
        ProviderMembership.objects.filter(role=doctor_role, is_active=True)
        .select_related("provider")
        .iterator()
    ):
        p = m.provider
        if not p or not p.specialty:
            continue
        name_norm = " ".join(str(p.specialty).split())
        if not name_norm:
            continue
        fac_id = p.facility_id
        fs = FacilitySpecialty.objects.filter(
            facility_id=fac_id, name__iexact=name_norm
        ).first()
        if fs is None:
            fs = FacilitySpecialty.objects.create(
                facility_id=fac_id, name=name_norm[:120]
            )
        ProviderProfile.objects.filter(pk=p.pk).update(facility_specialty_id=fs.id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20260502_1812"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitySpecialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="core.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["facility__name", "name"],
                "unique_together": {("facility", "name")},
            },
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="facility_specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="providers",
                to="core.facilityspecialty",
            ),
        ),
        migrations.RunPython(
            backfill_doctor_facility_specialties, migrations.RunPython.noop
        ),
    ]
