# Generated by Django 4.2.7 on 2026-05-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facility_specialty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientportalnotification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='providerportalnotification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='riderportalnotification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='patientpreference',
            name='lab_results_alerts',
        ),
        migrations.RemoveField(
            model_name='patientpreference',
            name='marketing_updates',
        ),
        migrations.RemoveField(
            model_name='patientpreference',
            name='medication_refill_reminders',
        ),
        migrations.RemoveField(
            model_name='patientpreference',
            name='privacy_mode',
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='appointment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_bookings', to='core.providerprofile'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='source',
            field=models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('doctor', 'Doctor')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='providerappointment',
            name='patient_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_appointment', to='core.patientbooking'),
        ),
        migrations.AddField(
            model_name='providerappointment',
            name='source',
            field=models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('doctor', 'Doctor')], default='provider', max_length=20),
        ),
        migrations.RemoveField(
            model_name='patientportalnotification',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='providerportalnotification',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='riderportalnotification',
            name='event_id',
        ),
    ]
