# Generated by Django 4.2.7 on 2026-05-08
# Hand-edited: daily_room_url + service_type_detail exist in DB → real RemoveField.
# dob_locked + name_locked never ran (migration 0005 was faked) → state-only removal.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patientportalnotification_unique_together_and_more'),
    ]

    operations = [
        # These columns actually exist in the DB — drop them for real.
        migrations.RemoveField(
            model_name='patientbooking',
            name='daily_room_url',
        ),
        migrations.RemoveField(
            model_name='patientbooking',
            name='service_type_detail',
        ),
        # These were added by migration 0005 which was faked (never ran against the DB).
        # Remove them from Django state only — no DB operation needed.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='patientprofile',
                    name='dob_locked',
                ),
                migrations.RemoveField(
                    model_name='patientprofile',
                    name='name_locked',
                ),
            ],
            database_operations=[],
        ),
    ]
