# Generated by Django 4.2.7 on 2026-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_drop_legacy_booking_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbooking',
            name='daily_room_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='meeting_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
