# Generated by Django 4.2.7 on 2026-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_virtual_meeting_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionqueueitem',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='commandbooking',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='commandincident',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='commandprovider',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='commandrider',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='complianceaudit',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='executivekpi',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientbooking',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientdiagnosticorder',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientprescription',
            name='delivery_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientprescription',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientrecordevent',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientsupportticket',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='performanceflag',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerappointment',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerconsultation',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerearningssnapshot',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerprescriptiontask',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='providerprotocol',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='revenueentry',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='riderearningssnapshot',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='riderhistoryentry',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='riderjob',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='idle', max_length=16),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
    ]
