# Generated by Django 4.2.7 on 2026-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_patientpreference_lab_results_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='name_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='name_locked',
            field=models.BooleanField(default=False),
        ),
    ]
