# Generated by Django 4.2.7 on 2026-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patientprofile_name_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermembership',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
