# Generated by Django 4.2.7 on 2026-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_providermembership_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerverificationdocument',
            name='document_type',
            field=models.CharField(choices=[('REGISTRATION_CERTIFICATE', 'Registration certificate'), ('OPERATING_LICENSE', 'Operating licence'), ('TAX_COMPLIANCE', 'Tax compliance'), ('ACCREDITATION', 'Accreditation'), ('LICENSE', 'License'), ('REGISTRATION', 'Registration'), ('ID', 'ID'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
